version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - node/install-packages
      - run: |
          node --version
          npm run build
  test:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - node/install-packages
      - run: |
          node --version
          npm run test:ci
workflows:
  build:
    jobs:
      - test
      - build
